### PR TITLE
Hide the add answer button on resolved questions

### PR DESCRIPTION
**Pull request by hLeePage**

### CODE REVIEW

**Comment by kurtisnelson** [comment]
This breaks out new (god) component Question.

**Comment by tjgragg** [comment]
What is a God component Question?

**Comment by kurtisnelson** [comment]
The Question component runs the entire page, so a god component.

**Comment by tjgragg** [comment]
Thank you for your explanation, good sir!

**Comment by hLeePage** [comment]
Sooooo...what's my next move here?

**Pull request closed without merging**
